name: CI

on:
  push:
    branches: [release/v1]
  pull_request:
    branches: [release/v1]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: ./setup-kube-score.sh
        env:
          KUBE_SCORE_VERSION: "1.19.0"

      - run: kube-score version
